/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ytx_ican_media_player_render_GraphicRenderer */

#ifndef _Included_com_ytx_ican_media_player_render_GraphicRenderer
#define _Included_com_ytx_ican_media_player_render_GraphicRenderer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ytx_ican_media_player_render_GraphicRenderer_FLOAT_SIZE_BYTES
#define com_ytx_ican_media_player_render_GraphicRenderer_FLOAT_SIZE_BYTES 4L
/*
 * Class:     com_ytx_ican_media_player_render_GraphicRenderer
 * Method:    native_init_opengl
 * Signature: ()V
 */
JNIEXPORT void JNICALL android_media_player_GraphicRenderer_native_init_opengl
  (JNIEnv *, jclass);

/*
 * Class:     com_ytx_ican_media_player_render_GraphicRenderer
 * Method:    native_resize_opengl
 * Signature: (II)V
 */
JNIEXPORT void JNICALL android_media_player_GraphicRenderer_native_resize_opengl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ytx_ican_media_player_render_GraphicRenderer
 * Method:    native_step_opengl
 * Signature: ()V
 */
JNIEXPORT void JNICALL android_media_player_GraphicRenderer_native_step_opengl
  (JNIEnv *, jobject);

/*
 * Class:     com_ytx_ican_media_player_render_GraphicRenderer
 * Method:    native_create_opengl
 * Signature: ()V
 */
JNIEXPORT void JNICALL android_media_player_GraphicRenderer_native_create_opengl
  (JNIEnv *, jobject);

/*
 * Class:     com_ytx_ican_media_player_render_GraphicRenderer
 * Method:    native_constructor_opengl
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL android_media_player_GraphicRenderer_native_constructor_opengl
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
