/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ytx_ican_ytxplayer_MainActivity */

#ifndef _Included_com_ytx_ican_ytxplayer_MainActivity
#define _Included_com_ytx_ican_ytxplayer_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ytx_ican_ytxplayer_MainActivity
 * Method:    setCmd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ytx_ican_ytxplayer_MainActivity_setCmd
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
