/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ytx_ican_media_player_YtxMediaPlayerTest */

#ifndef _Included_com_ytx_ican_media_player_YtxMediaPlayerTest
#define _Included_com_ytx_ican_media_player_YtxMediaPlayerTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ytx_ican_media_player_YtxMediaPlayerTest
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ytx_ican_media_player_YtxMediaPlayerTest_native_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_ytx_ican_media_player_YtxMediaPlayerTest
 * Method:    native_setup
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_ytx_ican_media_player_YtxMediaPlayerTest_native_1setup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ytx_ican_media_player_YtxMediaPlayerTest
 * Method:    native_finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ytx_ican_media_player_YtxMediaPlayerTest_native_1finalize
  (JNIEnv *, jobject);

/*
 * Class:     com_ytx_ican_media_player_YtxMediaPlayerTest
 * Method:    native_message_loop
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_ytx_ican_media_player_YtxMediaPlayerTest_native_1message_1loop
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
